name: terraform-service-apply

on:
  push:
    branches: ["main"]
    paths:
      - "service/**"   # service配下の変更だけで起動
      - ".github/workflows/terraform-service-apply.yml"

permissions:
  id-token: write
  contents: read

concurrency:
  group: terraform-service-main
  cancel-in-progress: false

jobs:
  apply:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: service  # ★ここが重要

    env:
      TF_IN_AUTOMATION: "true"
      TF_INPUT: "false"

    steps:
      - uses: actions/checkout@v4

      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.6

      # AWS OIDC
      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::941431937375:role/github-actions-terraform
          aws-region: ap-northeast-1

      - run: terraform fmt -check -recursive
      - run: terraform init -upgrade
      - run: terraform vaply -auto-approve

